site_name: Data Science & ML Engineering Portfolio
theme:
  name: material
  palette:
    primary: black
    accent: deep orange

nav:
  - Executive Summary: index.md
  - Core Architectures:
    - Multimodal IDP (LLM ETL): projects/invoice-etl.md
    - InsurTech Pricing Engine: projects/insurtech-pricing.md
    - AI Half-Marathon Inference: projects/half-marathon-ai.md