site_name: Data Science & ML Engineering Portfolio
theme:
  name: material
  palette:
    primary: black
    accent: deep orange

nav:
  - Executive Summary: index.md
  - Core Architectures:
    - Intelligent Document Processing (IDP): projekty/ocr-pipeline.md
    - Real Estate Value Estimation Model: projekty/ubezpieczenia.md
    - Customer Behavior & Classification: projekty/biegacz-cloud.md