site_name: Data Science & ML Engineering Portfolio
site_url: https://c8nraad.github.io/Portfolio-Data-Science/


theme:
  name: material

nav:
  - Executive Summary: index.md
  - Projects:
      - AI Invoice Intelligence: projekty/ocr-pipeline.md
      - Insurance Premium Advisor: projekty/ubezpieczenia.md
      - Endurance Dynamics: projekty/biegacz-cloud.md